/tmp/slurmd/job767536/slurm_script: line 2: BATCH: command not found
Traceback (most recent call last):
srun: error: compute180: task 0: Exited with exit code 1
  File "permutations.py", line 2, in <module>
    from optimizer import Optimizer
  File "/mnt/storage/home/rp14964/project_dir/Final_Project/experiment_code/optimizer.py", line 10, in <module>
    from network import Network
  File "/mnt/storage/home/rp14964/project_dir/Final_Project/experiment_code/network.py", line 5, in <module>
    from train import train_network
  File "/mnt/storage/home/rp14964/project_dir/Final_Project/experiment_code/train.py", line 1, in <module>
    from tf_attacks import mal_data_synthesis
  File "/mnt/storage/home/rp14964/project_dir/Final_Project/experiment_code/tf_attacks.py", line 3, in <module>
    import tensorflow as tf
  File "/mnt/storage/easybuild/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/mnt/storage/easybuild/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/mnt/storage/easybuild/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/mnt/storage/easybuild/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/mnt/storage/easybuild/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/mnt/storage/easybuild/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
